---
# Docker Compose file for ELK stack

# Prerequisite:
# Increase virtual memory settings
# https://www.elastic.co/guide/en/elasticsearch/reference/5.0/vm-max-map-count.html#vm-max-map-count

# Build with:
# docker-compose build

# Run with:
# docker-compose up

version: '2'
services:
  logstash:
    build:
      context: logstash
    ports:
      - "514:1514"
      - "514:1514/udp"
    depends_on:
      - elasticsearch
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: '-Xms3g -Xmx3g'

      # Name resolution option
      SYNLITE_SYSLOG_RESOLVE_IP2HOST: "false"
      SYNLITE_SYSLOG_NAMESERVER: "127.0.0.1"
      # Use port 1514 WITHIN container only due to JAVA priv ports problems
      SYNLITE_SYSLOG_TCP_PORT: "1514"
      SYNLITE_SYSLOG_UDP_PORT: "1514"
      SYNLITE_SYSLOG_ES_HOSTS: "elasticsearch"
      SYNLITE_SYSLOG_SYSLOG_TZ: "Pacific/Auckland"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: [ '9200:9200' ]
    volumes:
      # persistent data
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.0
    environment:
      # Set [server.name] option
      SERVER_NAME: "kibana.example.org"
      # Set [elasticseach.url] option
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      # Set [logging.quiet] option.  To reduce logging to stdout of container
      LOGGING_QUIET: "true"
    ports: [ '5601:5601' ]
    depends_on:
      - elasticsearch

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  es_data:
    driver: local
